### ISSUE TITLE
Returns not found error

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/exoframe-recipe-hobbit#2]
The `exoframe setup exoframe-recipe-hobbit` returns the 404 error if some containers are already running (e.g. from previous unsuccessful command execution).
Containers have to be stopped manually

**Comment by yamalight** [comment]
Cannot reproduce this.
I'm guessing this happens for the same reason #3 does ([explanation](https://github.com/hobbit-project/exoframe-recipe-hobbit/issues/3#issuecomment-404437249)).
