### ISSUE TITLE
GUI is not found at localhost

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/exoframe-recipe-hobbit#3]
Hi!
I have successfully executed the recipe (used the `localhost` as a domain for all asked questions).

Now the containers are running, but visiting the localhost I get the following error:
```
HTTP ERROR 404

Problem accessing /auth/realms/Hobbit/protocol/openid-connect/auth. Reason:

    Not Found
```
The redirected URL is 

`http://localhost/auth/realms/Hobbit/protocol/openid-connect/auth?client_id=Hobbit-GUI&redirect_uri=http%3A%2F%2Flocalhost%2F&state=9d2cc9fd-694b-442a-86c2-9ef22e4a48a0&nonce=9469abb4-5203-4dd7-a83c-9d59a9abbe24&response_mode=fragment&response_type=code&scope=openid`

Other related ports (8080, 8181, 15672) are not responding

**Comment by yamalight** [comment]
It seems like you've bound all the parts of hobbit to `localhost` - this won't work. I'm guessing you've also started Exoframe server on `localhost`. 
What happens with this setup is all requests to localhost get routed with load-balancing to one of the deployments. So every time you request `localhost`, you'll get a response from different service. 
I'm also guessing this is why #2 happened.

Both - Exoframe and Keycloak (and dependent GUI) - _require_ domains to work correctly.
You have two options: 
1) configure local dns (e.g. dnsmasq) and resolve your docker daemon with it
2) manually add aliases to `/etc/hosts`
Then you need to restart Exoframe server and whole Hobbit deployment with unique domains.

**Comment by smirnp** [comment]
Thanks! Separate domains helped.
